version: 2

sources: 
- name: analytics
  schema: production
  description: This is the adventures works production postgres database replica.
  tables:
    - name: raw_billofmaterials 
      description: This table contains items required to make bicycles and bicycle subassemblies.
    - name: raw_location
    - name: raw_product
    - name: raw_productcategory
    - name: raw_productinventory
    - name: raw_productsubcategory
    - name: raw_scrapreason
    - name: raw_transactionhistory
      description: Record of each purchase order, sales order, or work order transaction year to date.
    - name: raw_transactionhistoryarchive
    - name: raw_workorder
    - name: raw_workorderrouting
      description: Work order details.

